// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-D8iumSFE6U0PYn-J5vpTg4_oYPY6O8A',
    appId: '1:19465852024:web:5e5ace18d12d09cac1898d',
    messagingSenderId: '19465852024',
    projectId: 'inventory-management-fc586',
    authDomain: 'inventory-management-fc586.firebaseapp.com',
    storageBucket: 'inventory-management-fc586.appspot.com',
    measurementId: 'G-HXYXJFHRKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAvtVNt_YeAHB-TzMYA9Xf8vLH53Glqqw',
    appId: '1:19465852024:android:40ca225ed797bb99c1898d',
    messagingSenderId: '19465852024',
    projectId: 'inventory-management-fc586',
    storageBucket: 'inventory-management-fc586.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC216GnXjW9otQdDU9907NXY4Q2Elkrj34',
    appId: '1:19465852024:ios:5701757b0c3749cfc1898d',
    messagingSenderId: '19465852024',
    projectId: 'inventory-management-fc586',
    storageBucket: 'inventory-management-fc586.appspot.com',
    iosBundleId: 'com.example.shopManagerUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-D8iumSFE6U0PYn-J5vpTg4_oYPY6O8A',
    appId: '1:19465852024:web:799a353ca09c354cc1898d',
    messagingSenderId: '19465852024',
    projectId: 'inventory-management-fc586',
    authDomain: 'inventory-management-fc586.firebaseapp.com',
    storageBucket: 'inventory-management-fc586.appspot.com',
    measurementId: 'G-9G7P3NKWV2',
  );
}
